ARG BALENA_ARCH=%%BALENA_ARCH%%

FROM balenalib/$BALENA_ARCH-alpine:3.14
WORKDIR /usr/src

RUN install_packages curl jq
COPY start.sh start.sh

#dev-cmd-live=balena-idle
CMD [ "/bin/bash", "/usr/src/start.sh" ]